### ISSUE TITLE
Add support for removing labels automatically 

### ISSUE THREAD

**Issue by nsivabalan** [Renato66/auto-label#23]
Is there a way to auto remove labels similar to how its automatically added?

for eg: when someone from the community responds to an user issue and adds "awaiting-user-input" label. Once the user/author responds w/ some input requested, the "awaiting-user-input" label should be automatically removed. 

Basically folks who are looking to help with issues, need a way to filter out issues that are waiting in the queue to be attended. Those that are awaiting user/author inputs can be filtered out if we have this auto removal of labels.

**Comment by nsivabalan** [comment]
May I know iff existing template add labels when an issue is edited? 
For eg,
```
name: Labeling new issue
on:
  issues:
    types: ['opened','edited']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          labels-synonyms: '{"bug":["error","need fix","not working"],"enhancement":["upgrade"],"question":["help"]}'
          labels-not-allowed: '["good first issue"]'
          default-labels: '["help wanted"]'
```

Lets say this is our workflow.
Once user creates an issue, "help wanted" will be added by bot.
And if someone from community responds and removes the label "help wanted". May be asked for more input from author/user. 
Following this, if user edits the issue, will "help wanted" label be automatically added?

**Comment by nsivabalan** [comment]
I tried something like below, but looks like the format is wrong. even "opened" is not working.

```
cat .github/workflows/issue.yml
name: Labeling new issue
on:
  issues:
    types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          labels-synonyms: '{"bug":["error","need fix","not working"],"enhancement":["upgrade"],"question":["help"]}'
          labels-not-allowed: '["awaiting user input"]'
          default-labels: '["help wanted first time"]'
on:
  issues:
    types: ['edited']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          labels-synonyms: '{"bug":["error","need fix","not working"],"enhancement":["upgrade"],"question":["help"]}'
          default-labels: '["help wanted"]'
```
