### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by dantebarba** [Renato66/auto-label#32]
Since yesterday the plugin is raising an error when building:

```bash
  Step 3/4 : RUN npm install --production
   ---> Running in 3973b404579b
  npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
  npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
  npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
  npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
  npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
  npm WARN deprecated har-validator@5.1.5: this library is no longer supported
  npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  npm ERR! Unexpected end of JSON input while parsing near ''
  
  npm ERR! A complete log of this run can be found in:
```

**Comment by Renato66** [comment]
could you provide more info about this error ? 
at this action log here https://github.com/Renato66/auto-label/actions/runs/1583628486
nothing has error; could you share the yml file ?

**Comment by Renato66** [comment]
since it has no activity i will be closing this issue, feel free to reopen it

**Comment by dantebarba** [comment]
Sorry @Renato66 I didn't have time to check the issue. 

My YAML:

```yaml
name: Labeling new issue
on:
  issues:
    types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          default-labels: '["back-end"]'
```
