### ISSUE TITLE
Error parsing issue 

### ISSUE THREAD

**Issue by dantebarba** [Renato66/auto-label#35]
Hey,

Not always but sometimes the following issue arises:

> *** running renato66/auto-label version 2.1.2 ***
> Getting repository labels...
> Repository labels found: 12
> Reading labels in issue...
> (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
> Error: Cannot read property 'replace' of null
>     at Object.getIssueLabels (/lib/functions.js:66:39)
>     at /lib/main.js:37:45
>     at Generator.next (<anonymous>)
>     at fulfilled (/lib/main.js:5:5[8](https://github.com/IB5k/foodshedzoho/runs/5696779806?check_suite_focus=true#step:3:8))
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:1) [DEP00[18](https://github.com/IB5k/foodshedzoho/runs/5696779806?check_suite_focus=true#step:3:18)] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My YAML:

```yaml
name: Labeling new issue
on:
  issues:
    types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          default-labels: '["back-end"]'
```
